apiVersion: v1
kind: ConfigMap
metadata:
  name: xtask-config
  namespace: xtask-platform
data:
  NODE_ENV: "production"
  PORT: "5000"
  JWT_SECRET: "xtask-secret-key"
  # Agregar otras variables de configuración no sensibles aquí